- name: Install Apt Packages
  apt: name-{{item}}
  with_items:
    - "{ snapd }"
    - "{ remmina }"
    - "{ vim }"
    - "{ wget }"
    - "{ git }"
    - "{ zsh }"
    - "{ preload }"
    - "{ htop }"

- name: Install Snap Packages
  snap: name={{item}}
  with_items:
    - "{ starship }"
    - "{ discord }"

- name: Install CLASSIC Snap Packages  ## classic can ONLY be specified for individual packages - lists cannot be used :(
  snap: 
    name: code
    classic: yes

