- name: Install Apt Packages
  apt: name-{{item}}
  with_items:
    - "{ snapd }"
    - "{ remmina }"
    - "{ vim }"
    - "{ wget }"
    - "{ git }"
    - "{ zsh }"
    - "{ preload }"
    - "{ htop }"

- name: Install Snap Packages
  snap: name={{item}}
  with_items:
    - "{ starship }"
    - "{ discord }"

- name: Install CLASSIC Snap Packages
  snap: name={{item}}
    classic: yes
  with_items:
    - "{ code }"

